name: Daily Telecom Newsletter

on:
  schedule:
    # 07:00 UTC = 08:00 Lisbon time, every weekday
    - cron: '0 7 * * 1-5'

  # Run manually anytime from the Actions tab
  workflow_dispatch:

jobs:
  send-newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run newsletter script
        env:
          CLAUDE_API_KEY:       ${{ secrets.CLAUDE_API_KEY }}
          SHEET_URL_FEEDS:      ${{ secrets.SHEET_URL_FEEDS }}
          SHEET_URL_KEYWORDS:   ${{ secrets.SHEET_URL_KEYWORDS }}
          SHEET_URL_RECIPIENTS: ${{ secrets.SHEET_URL_RECIPIENTS }}
          GMAIL_ADDRESS:        ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD:   ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python newsletter.py
